language: csharp
mono: none
dotnet: 2.0.3

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test MTAServiceStatus.Tests/MTAServiceStatus.Tests.cspr

# blocklist
branches:
  except:
  - gh-pages
  